### ISSUE TITLE
SECCHI data can not be loaded from GSFC and IAS database through JHV

### ISSUE THREAD

**Issue by marialda27** [Helioviewer-Project/JHelioviewer-SWHV#116]
Hi,
we work at the Institute of Theoretical and Experimental Astronomy in Argentina, and we are having problems trying to open SECCHI data from any database.
The error message is:
Error getting data. Error found during JPX creation: no images were found for the requested time range.
But a colleague in another institution can load the data.
Please, could you help us solve this problem?
Mariana

**Comment by ebuchlin** [comment]
Hello,
What time range are you using, and what is the URI of the JPX? (it is shown for example in the JHelioViewer terminal output in linux). I just tried e.g. STEREO-A EUVI 195 2017-10-15T05:59:09 to 2017-10-17T05:59:09 from IAS in JHV, I got jpip://helioviewer.ias.u-psud.fr:8080/movies/STEREO_A_SECCHI_EUVI_195_F2017-10-15T05.59.09Z_T2017-10-17T05.59.09ZB1800L.jpx and the expected movie in JHV. Then the URL of this JPX is https://helioviewer.ias.u-psud.fr/jp2/movies/STEREO_A_SECCHI_EUVI_195_F2017-10-15T05.59.09Z_T2017-10-17T05.59.09ZB1800L.jpx . Can you access this URL? (from a browser, or just downloading it with wget or curl)
Eric (IAS)

**Comment by marialda27** [comment]
Hello Eric,
thanks in advance for your time and help. 
The range is 2010-12-23, from 00:00:00 to 10:12:00. I first loaded the SDO data successfully, but when I tried to load the SECCHI data, this was not possible:

SDO from IAS

2019-10-18 15:00:02,598 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"frames":97,"message":null,"uri":"jpip://helioviewer.ias.u-psud.fr:8080/movies/SDO_AIA_171_F2019-10-16T17.12.33Z_T2019-10-18T17.12.33ZB1800L.jpx"}
2019-10-18 15:00:29,350 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"frames":98,"message":null,"uri":"jpip://helioviewer.ias.u-psud.fr:8080/movies/SDO_AIA_304_F2010-12-23T00.00.00Z_T2010-12-23T10.12.33ZB382L.jpx"}

SECCHI from IAS

2019-10-18 15:01:30,140 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"error":"Error encountered during JPX creation: No images were found for the requested time range.","uri":null}
2019-10-18 15:01:30,141 [JHVWorker-MAIN--LoadRemote] ERROR root - Data query returned error: Error encountered during JPX creation: No images were found for the requested time range.

SECCHI from GFSC

2019-10-18 15:10:44,635 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"error":"Error encountered during JPX creation: No images were found for the requested time range.","uri":null}
2019-10-18 15:10:44,635 [JHVWorker-MAIN--LoadRemote] ERROR root - Data query returned error: Error encountered during JPX creation: No images were found for the requested time range.

Thanks again,
Mariana

**Comment by bogdanni** [comment]
Can you please be more explicit, i.e. data range, spacecraft, instrument, wavelength?

**Comment by marialda27** [comment]
Yes, of course, I have problems with:
day: 2010-12-23
range: 00:00:00 to 10:12:00
spacecraft: SECCHI
instrument: EUVI A, EUVI B
wavelengths: 171, 195, 284, 304.
Thanks in advance for your help and time.
Mariana

**Comment by bogdanni** [comment]
GSFC works for me. IAS seems to have a data gap.
<img width="335" alt="secchi" src="https://user-images.githubusercontent.com/1223825/67119918-79390f00-f1e8-11e9-9f15-0fb0521b1b9a.png">
I understand you can load other data sets, this one should work too. Could you please try to load it via menu item File->New Image Layer and try to reproduce the values of the dialog box in my screenshot?

**Comment by ebuchlin** [comment]
We seem indeed to have a data gap between 2010-10-20T09:40 and 2011-01-01T00:05 for STEREO-A, and between 2010-10-04T11:56 and 2011-01-01T00:06 for STEREO-B. We are going to fill this gap (and look again for others). Thanks for the report!

**Comment by marialda27** [comment]
Hi all,
thanks for your help. I tried with  File->New Image Layer 
![imagen](https://user-images.githubusercontent.com/38140031/67591325-8fd4ee00-f733-11e9-98c1-f7bb397e82df.png)
but then:
![imagen](https://user-images.githubusercontent.com/38140031/67591443-d88ca700-f733-11e9-9906-04ccd2566755.png)
the same result :( .

**Comment by bogdanni** [comment]
The error is different: initially, there were no images found on the IAS server (that is confirmed as a coverage gap), now, there is a timeout in the connection with the server. I checked immediately after your reply and I could load that dataset.

I can think of three possibilities:
1. your network connection is flaky;
2. GSFC server was overloaded at that precise moment you tried;
3. you are behind a firewall that blocks port 8090 and lets the connection lapse without returning an error right away.

For the first two, just retrying after a while would fix it.
For the last one: I've seen successful logs only for the IAS server which uses port 8080 which is a bit more common and may not be blocked by a firewall. Can you please try to load any other recent dataset (like AIA 171 between 2019-10-23 and 2019-10-25) available on GSFC or ROB servers and post the log from the terminal? If the third hypothesis is right, you will always get connection timeout for GSFC and ROB data.

**Comment by marialda27** [comment]
Hi,
I tried the first 2 options several times and they do not work.
Then I tried to load your request:
**With GSFC it did not work:** 
2019-10-28 11:16:45,043 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"frames":97,"message":null,"uri":"jpip://helioviewer.org:8090/movies/SDO_AIA_171_F2019-10-23T00.00.00Z_T2019-10-25T00.00.00ZB1800L.jpx"}
2019-10-28 11:18:56,364 [JHVWorker-MAIN--LoadRemote] DEBUG root - loadView("jpip://helioviewer.org:8090/movies/SDO_AIA_171_F2019-10-23T00.00.00Z_T2019-10-25T00.00.00ZB1800L.jpx") 
java.io.IOException: java.net.ConnectException: Connection timed out
        at org.helioviewer.jhv.view.j2k.io.http.HTTPSocket.<init>(HTTPSocket.java:49)
        at org.helioviewer.jhv.view.j2k.io.jpip.JPIPSocket.<init>(JPIPSocket.java:38)
        at org.helioviewer.jhv.view.j2k.J2KReader.<init>(J2KReader.java:38)
        at org.helioviewer.jhv.view.j2k.J2KView.<init>(J2KView.java:71)
        at org.helioviewer.jhv.io.LoadViewTask.loadView(LoadViewTask.java:70)
        at org.helioviewer.jhv.io.LoadViewTask.requestAndOpenRemoteFile(LoadViewTask.java:84)
        at org.helioviewer.jhv.io.LoadRemoteTask.backgroundWork(LoadRemoteTask.java:26)
        at org.helioviewer.jhv.io.LoadRemoteTask.backgroundWork(LoadRemoteTask.java:12)
        at org.helioviewer.jhv.threads.JHVWorker.doInBackground(JHVWorker.java:19)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:454)
        at sun.nio.ch.Net.connect(Net.java:446)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        at org.helioviewer.jhv.view.j2k.io.http.HTTPSocket.<init>(HTTPSocket.java:46)
        ... 14 more
2019-10-28 11:18:56,366 [JHVWorker-MAIN--LoadRemote] ERROR root - An error occured while opening the remote file: 
java.io.IOException: java.io.IOException: java.net.ConnectException: Connection timed out
        at org.helioviewer.jhv.io.LoadViewTask.loadView(LoadViewTask.java:76)
        at org.helioviewer.jhv.io.LoadViewTask.requestAndOpenRemoteFile(LoadViewTask.java:84)
        at org.helioviewer.jhv.io.LoadRemoteTask.backgroundWork(LoadRemoteTask.java:26)
        at org.helioviewer.jhv.io.LoadRemoteTask.backgroundWork(LoadRemoteTask.java:12)
        at org.helioviewer.jhv.threads.JHVWorker.doInBackground(JHVWorker.java:19)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.ConnectException: Connection timed out
        at org.helioviewer.jhv.view.j2k.io.http.HTTPSocket.<init>(HTTPSocket.java:49)
        at org.helioviewer.jhv.view.j2k.io.jpip.JPIPSocket.<init>(JPIPSocket.java:38)
        at org.helioviewer.jhv.view.j2k.J2KReader.<init>(J2KReader.java:38)
        at org.helioviewer.jhv.view.j2k.J2KView.<init>(J2KView.java:71)
        at org.helioviewer.jhv.io.LoadViewTask.loadView(LoadViewTask.java:70)
        ... 10 more
Caused by: java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:454)
        at sun.nio.ch.Net.connect(Net.java:446)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        at org.helioviewer.jhv.view.j2k.io.http.HTTPSocket.<init>(HTTPSocket.java:46)
        ... 14 more


**With ROB it worked:**
2019-10-28 11:11:08,047 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"frames":97,"message":null,"uri":"jpip://swhv.oma.be:8090/movies/SDO_AIA_AIA_171_F2019-10-23T00.00.00Z_T2019-10-25T00.00.00ZB1800L.jpx"}
kdu_jni.KduException
        at kdu_jni.Kdu_compressed_source.Close(Native Method)
        at org.helioviewer.jhv.view.j2k.J2KView.kduDestroy(J2KView.java:155)
        at org.helioviewer.jhv.view.j2k.J2KView.lambda$abolish$0(J2KView.java:148)
        at java.lang.Thread.run(Thread.java:748)
kdu_jni.KduException
        at kdu_jni.Kdu_compressed_source.Close(Native Method)
        at org.helioviewer.jhv.view.j2k.J2KView.kduDestroy(J2KView.java:155)
        at org.helioviewer.jhv.view.j2k.J2KView.lambda$abolish$0(J2KView.java:148)
        at java.lang.Thread.run(Thread.java:748)

**Comment by bogdanni** [comment]
The GSFC trace clearly shows timeout when connecting to the image server (aka jpip server).
The ROB trace shows a decode exception which may or not be related to loading data from ROB server, because those exceptions occur asynchronously.

Can you please confirm:
1. Loading a recent movie from ROB actually worked, i.e., you can see and manipulate the movie.
2. Does your site have a network firewall?

**Comment by wafels** [comment]
I just tried the GSFC server for AIA 171 data 2019-10-23 - 2019-10-25 and
obtained a movie with no problems.  I used JHelioviewer Version 2.15.3.9221
and Version 2.15.7.9411.

**Comment by marialda27** [comment]
Hi all,
Sorry for the delay. I talked to the system managers of the institute and they confirmed that we were behind a firewall that blocks port 8090. They solved the problem and now I can load the data.
Thank you very much for your help.
M.

**Comment by bogdanni** [comment]
Mariana, thank you for the persistence in getting to the bottom of this.
