### ISSUE TITLE
JHV fatal error during first start cannot load library gluegen_rt.dll

### ISSUE THREAD

**Issue by roalt** [Helioviewer-Project/JHelioviewer-SWHV#161]
Following error message was generated at starting the beta version:

Log:
2021-04-08 10:35:02,006 [main] INFO  root - JHelioviewer started with command-line options: 
2021-04-08 10:35:02,373 [main] INFO  root - JHV/SWHV-4.0.1.10215 (amd64 Windows 10 10.0) AdoptOpenJDK JRE 11.0.10 4.0GB 12CPU
2021-04-08 10:35:02,375 [main] WARN  root - Settings > Could not load settings
2021-04-08 10:35:03,251 [main] TRACE class org.ehcache.core.Ehcache-JPIPLevel - Initializing
2021-04-08 10:35:03,287 [main] DEBUG class org.ehcache.core.Ehcache-JPIPLevel - Initialize successful.
2021-04-08 10:35:03,309 [main] TRACE class org.ehcache.core.Ehcache-JPIPStream - Initializing
2021-04-08 10:35:03,325 [main] DEBUG class org.ehcache.core.Ehcache-JPIPStream - Initialize successful.
2021-04-08 10:35:03,901 [AWT-EventQueue-0] INFO  root - Start main window
2021-04-08 10:35:04,448 [AWT-EventQueue-0] ERROR root - Runtime exception
java.lang.UnsatisfiedLinkError: Can't load library: C:\Program Files\JHelioviewer\bin\natives\windows-amd64\\gluegen_rt.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at org.helioviewer.jhv.opengl.GLHelper.createGLCanvas(GLHelper.java:79)
	at org.helioviewer.jhv.gui.JHVFrame.prepare(JHVFrame.java:64)
	at org.helioviewer.jhv.JHelioviewer.lambda$main$0(JHelioviewer.java:77)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by bogdanni** [comment]
This usually happens when there is a problem finding your user account temporary directory.
Is there something special about your account: non-ASCII, stored on a network directory?

Type in taskbar search: "environment variables", it will offer a match "Edit the system environment variables (Control Panel)". There should be TEMP and TMP something like mine in the attached. In that directory should be a directory called "jogamp_0000".

![envvar](https://user-images.githubusercontent.com/1223825/114010877-e0c39e00-9864-11eb-9a84-c579e2c7483e.png)

**Comment by bogdanni** [comment]
Please open a report with more details about the computer you are trying to run it on.
