### ISSUE TITLE
Can't download movie from JHelioviewer

### ISSUE THREAD

**Issue by Jenny0Chen** [Helioviewer-Project/JHelioviewer-SWHV#181]
Use Mac Laptop, download and install JHelioviewer_4_1_1.dmg, I type "Recording" button, I can see the movie on the screen. But there isn't pop up window, I can't download the movie to my local directory.
Could you tell me how can I download movie to my local directory?
Thanks!

**Comment by bogdanni** [comment]
Thanks for the report. What language do you use in the interface of your Mac?

I had the idea that maybe it could be an issue with an Unicode user name, but then I saw https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437, i.e., Posix user names should essentially be restricted to ASCII. Trying to create a user with a Chinese name in a virtual machine still gave me an ASCII user name.

To verify, could you please open Applications > Utilities > Terminal and enter command `pwd`. It should print something like `/Users/chen`, i.e., only ASCII characters. Could you please check?

**Comment by bogdanni** [comment]
Sorry, I initially typed a reply asking about language of your computer, but then I noticed in the email report that you mentioned English as language of the computer. Could you please give some details about the model of the laptop and which version of the macOS.

I did a screen capture of the application, could you please check it? You should be able to record even without a solar image sequence loaded.
https://user-images.githubusercontent.com/1223825/141433535-8682ea67-d001-44e7-b4a3-0aefb4f455e6.mov

**Comment by bogdanni** [comment]
In your home directory, there should be a directory JHelioviewer-SWHV/Exports. Is it empty?

**Comment by Jenny0Chen** [comment]
Hi, Bogdanni, Thanks for your kindly reply. My laptop is MacBook Pro (Retina, 15-inch, Mid 2015), Processor 2.5 GHz Quad-Core Intel Core i7, Graphics AMD Radeon R9 M370X 2 GB Intel Iris Pro 1536 MB. mass version is macOS Catalina Version 10.15.7.
When I point the "record" button, I can see the Jhelioview's movies on the screen, but there is not pop up window to save the movie.
In my home directory, there is a directory JHelioviewer-SWHV/Exports. It is empty.
Do you know what's the problem?

**Comment by bogdanni** [comment]
Could you please do the following:

- open the terminal application from Applications > Utilities > Terminal
- change directory inside the JHV application bundle: 
  `cd /Applications/JHelioviewer.app/Contents/Resources/app/classes`
- run JHV from terminal: 
  `../../jre.bundle/Contents/Home/bin/java --add-exports java.desktop/sun.awt=ALL-UNNAMED -cp JHelioviewer.jar:natives-macos.jar org.helioviewer.jhv.JHelioviewer`
- try to export a movie and after the CPU spike ends, paste into this issue what was printed by JHV in the terminal.

Thanks!

**Comment by Jenny0Chen** [comment]
Thanks for your reply. I tried you commands in the terminal and run JHV from terminal. Following are the print in my terminal.
There isn't pop up window, after the CPU spike ends. I can't download yet. Thanks for your patience!

jiechen@192 classes % ../../jre.bundle/Contents/Home/bin/java --add-exports java.desktop/sun.awt=ALL-UNNAMED -cp JHelioviewer.jar:natives-macos.jar org.helioviewer.jhv.JHelioviewer
2021-11-15 21:10:39,442 [main] INFO  root - JHelioviewer started with command-line options: 
2021-11-15 21:10:39,482 [main] INFO  root - JHV/SWHV-4.1.1.10360 (x86_64 Mac OS X 10.15.7) Eclipse Adoptium JRE 17 4.0GB 8CPU
2021-11-15 21:10:40,963 [main] ERROR org.ehcache.core.EhcacheManager - Initialize failed.
2021-11-15 21:10:40,964 [main] ERROR root - JPIP cache initialization error
org.ehcache.StateTransitionException: Persistence directory already locked by another process: /Users/jiechen/JHelioviewer-SWHV/Cache/JPIPLevel-3
	at org.ehcache.core.StatusTransitioner$Transition.failed(StatusTransitioner.java:235)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:605)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:75)
	at org.helioviewer.jhv.view.j2k.io.jpip.JPIPCacheManager.init(JPIPCacheManager.java:46)
	at org.helioviewer.jhv.JHVInit.init(JHVInit.java:35)
	at org.helioviewer.jhv.JHelioviewer.main(JHelioviewer.java:63)
Caused by: java.lang.RuntimeException: Persistence directory already locked by another process: /Users/jiechen/JHelioviewer-SWHV/Cache/JPIPLevel-3
	at org.ehcache.impl.persistence.DefaultLocalPersistenceService.internalStart(DefaultLocalPersistenceService.java:105)
	at org.ehcache.impl.persistence.DefaultLocalPersistenceService.start(DefaultLocalPersistenceService.java:75)
	at org.ehcache.core.spi.ServiceLocator.startAllServices(ServiceLocator.java:128)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:577)
	... 4 more
2021-11-15 21:10:41,676 [AWT-EventQueue-0] INFO  root - Start main window
2021-11-15 21:10:44,621 [AWT-EventQueue-0] INFO  root - Load bundled plugins
2021-11-15 21:10:45,101 [AWT-EventQueue-0] INFO  root - GLInfo > OpenGL 4.1 ATI-3.10.18
Nov 15, 2021 1:10:45 PM org.astrogrid.samp.hub.Hub runHub
WARNING: Failed to start SAMP hub profile Standard
java.io.IOException: A hub is already running
	at org.astrogrid.samp.xmlrpc.StandardHubProfile.start(StandardHubProfile.java:99)
	at org.astrogrid.samp.hub.Hub.startProfile(Hub.java:143)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:499)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:543)
	at org.helioviewer.jhv.io.SampClient.lambda$init$0(SampClient.java:47)
	at java.base/java.lang.Thread.run(Thread.java:833)

Nov 15, 2021 1:10:45 PM org.astrogrid.samp.hub.Hub runHub
WARNING: Failed to start SAMP hub profile Web
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
	at org.astrogrid.samp.web.WebHubProfile$ServerFactory.createServerSocket(WebHubProfile.java:480)
	at org.astrogrid.samp.web.WebHubProfile$ServerFactory.createSampXmlRpcServer(WebHubProfile.java:299)
	at org.astrogrid.samp.web.WebHubProfile.start(WebHubProfile.java:90)
	at org.astrogrid.samp.hub.Hub.startProfile(Hub.java:143)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:499)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:543)
	at org.helioviewer.jhv.io.SampClient.lambda$init$0(SampClient.java:47)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.io.IOException: No SAMP profiles started: java.io.IOException: A hub is already running
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:514)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:543)
	at org.helioviewer.jhv.io.SampClient.lambda$init$0(SampClient.java:47)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: A hub is already running
	at org.astrogrid.samp.xmlrpc.StandardHubProfile.start(StandardHubProfile.java:99)
	at org.astrogrid.samp.hub.Hub.startProfile(Hub.java:143)
	at org.astrogrid.samp.hub.Hub.runHub(Hub.java:499)
	... 3 more
2021-11-15 21:10:45,709 [AWT-EventQueue-0] ERROR root - LoadSources error: ESAC
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:222)
	at org.helioviewer.jhv.io.JSONUtils.get(JSONUtils.java:29)
	at org.helioviewer.jhv.io.JSONUtils.get(JSONUtils.java:40)
	at org.helioviewer.jhv.io.LoadSources.call(LoadSources.java:50)
	at org.helioviewer.jhv.io.LoadSources.call(LoadSources.java:21)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
jiechen@192 classes % ../../jre.bundle/Contents/Home/bin/java --add-exports java.desktop/sun.awt=ALL-UNNAMED -cp JHelioviewer.jar:natives-macos.jar org.helioviewer.jhv.JHelioviewer
2021-11-15 21:17:40,090 [main] INFO  root - JHelioviewer started with command-line options: 
2021-11-15 21:17:40,152 [main] INFO  root - JHV/SWHV-4.1.1.10360 (x86_64 Mac OS X 10.15.7) Eclipse Adoptium JRE 17 4.0GB 8CPU
2021-11-15 21:17:42,230 [main] TRACE class org.ehcache.core.Ehcache-JPIPLevel - Initializing
2021-11-15 21:17:42,268 [main] DEBUG class org.ehcache.core.Ehcache-JPIPLevel - Initialize successful.
2021-11-15 21:17:42,289 [main] TRACE class org.ehcache.core.Ehcache-JPIPStream - Initializing
2021-11-15 21:17:42,307 [main] DEBUG class org.ehcache.core.Ehcache-JPIPStream - Initialize successful.
2021-11-15 21:17:42,972 [AWT-EventQueue-0] INFO  root - Start main window
2021-11-15 21:17:46,522 [AWT-EventQueue-0] INFO  root - Load bundled plugins
2021-11-15 21:17:47,005 [AWT-EventQueue-0] INFO  root - GLInfo > OpenGL 4.1 ATI-3.10.18
2021-11-15 21:17:48,091 [AWT-EventQueue-0] ERROR root - LoadSources error: ESAC
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:222)
	at org.helioviewer.jhv.io.JSONUtils.get(JSONUtils.java:29)
	at org.helioviewer.jhv.io.JSONUtils.get(JSONUtils.java:40)
	at org.helioviewer.jhv.io.LoadSources.call(LoadSources.java:50)
	at org.helioviewer.jhv.io.LoadSources.call(LoadSources.java:21)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by bogdanni** [comment]
At first launch, it seems you had another instance running. In any case, it should not matter.

Now could you please try the following:
1. close all JHV instances which may be running
2. remove the directory JHelioviewer-SWHV from your home directory
3. start JHV normally, by double-clicking the icon
4. try to export a movie like above
5. (without closing JHV) in directory JHelioviewer-SWHV/Cache there should be a directory named export with many numbers (like, export14557472157666975214). In that directory there should be two files, one fferr, one ffout, again followed by many numbers and .tmp (like, fferr16540613447964462608.tmp, ffout3583006830684501868.tmp)

Could you please post here the two file?
Thank you for bearing with me!

**Comment by Jenny0Chen** [comment]
Thanks for your patience!
Following your suggestions, I do the following:
1. close all JHV instances, and I also shut down the laptop and restart it.
2. remove the directory JHelioviewer-SWHV from your home directory
3. start JHV normally, by double-clicking the icon 
4. there is not pop-up dialogue yet.
5. (without closing JHV) in directory JHelioviewer-SWHV/Cache, there is a directory named export with numbers:export6183527254849584593, but in this export directory, there is not any file.
6. I tried the above steps in the terminal using the guides that you send me yesterday, it is the same. I can't find any file in the export directory, both in JHelioviewer-SWHV/Cache and JHelioviewer-SWHV/Exports.
I don't know the reason. Thanks a lot!

**Comment by bogdanni** [comment]
Hmm, this is really strange!
I have a laptop exactly like yours (MacBook Pro 15-inch, Mid 2015), running macOS 10.15.7.

Do you try to record exactly like in this screen capture (https://user-images.githubusercontent.com/1223825/141433535-8682ea67-d001-44e7-b4a3-0aefb4f455e6.mov) I posted earlier?

**Comment by Jenny0Chen** [comment]
Hi, it is fixed now. I made a very stupid mistake. I thought the triangle button (black) is the record button, I am waiting and waiting, there was no pop-up dialogue. Now I realize the round (brown) button is the record button. Now, the pop-up dialogue appears. I am really sorry for using your time. Thanks!

**Comment by bogdanni** [comment]
It's dark red actually, I was trying to get the shade from an old stereo ;)
Glad it works and to be of help.
