### ISSUE TITLE
SchemaLoader unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by greyfade** [Helioviewer-Project/JHelioviewer-SWHV#20]
This error pops up immediately after startup, after freshly installing the program.

```
Uncaught Exception detected.

Configuration:
JHelioviewer - Version: 2.10.5
JHelioviewer - Revision: 7844
Java Virtual Machine - Name: OpenJDK 64-Bit Server VM
Java Virtual Machine - Vendor: Oracle Corporation
Java Virtual Machine - Version: 24.95-b01
JRE Specification - Version: 1.7
Operating System - Name: Linux
Operating System - Architecture: amd64
Operating System - Version: 4.6.4-1-ARCH

Date: Fri Jul 22 21:16:49 UTC 2016
Thread: Thread[AWT-EventQueue-0,6,main]
Message: org/everit/json/schema/loader/SchemaLoader : Unsupported major.minor version 52.0

Stacktrace:
java.lang.UnsupportedClassVersionError
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at org.helioviewer.jhv.io.DataSources.loadSources(DataSources.java:99)
at org.helioviewer.jhv.JavaHelioViewer$1.run(JavaHelioViewer.java:111)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
at java.awt.EventQueue.access$300(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:706)
at java.awt.EventQueue$3.run(EventQueue.java:704)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Log:
2016-07-22 14:16:46,569 [main] INFO  root - JHelioviewer started with command-line options:
2016-07-22 14:16:46,580 [main] DEBUG root - LogSettings.update() > Log settings modified. Update changes.
2016-07-22 14:16:46,583 [main] INFO  root - Store log settings to /home/greywolf/JHelioviewer-SWHV/Settings/log4j.properties
2016-07-22 14:16:46,588 [main] INFO  root - Running 2.10.5 7844
2016-07-22 14:16:46,588 [main] INFO  root - Initializing JHelioviewer
2016-07-22 14:16:46,590 [main] INFO  root - OS: linux - arch: x86-64 - java arch: 64
2016-07-22 14:16:46,590 [main] DEBUG root - Instantiate Kakadu engine
2016-07-22 14:16:46,591 [main] DEBUG root - Saving stream to /home/greywolf/JHelioviewer-SWHV/Libs/libkdu_v77R.so
2016-07-22 14:16:46,603 [main] DEBUG root - Saving stream to /home/greywolf/JHelioviewer-SWHV/Libs/libkdu_a77R.so
2016-07-22 14:16:46,626 [main] DEBUG root - Saving stream to /home/greywolf/JHelioviewer-SWHV/Libs/libkdu_jni.so
2016-07-22 14:16:47,757 [AWT-EventQueue-0] INFO  root - Start main window
2016-07-22 14:16:49,099 [AWT-EventQueue-0] FATAL root - Runtime exception
java.lang.UnsupportedClassVersionError: org/everit/json/schema/loader/SchemaLoader : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.helioviewer.jhv.io.DataSources.loadSources(DataSources.java:99)
	at org.helioviewer.jhv.JavaHelioViewer$1.run(JavaHelioViewer.java:111)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by bogdanni** [comment]
Could you please run it with Java 8?
While the feature leading to this error is not essential and could easily be skipped now, I expect Java 8 to become a hard requirement soon.

**Comment by greyfade** [comment]
It appears to work in Java 8.

I always forget that's a thing. :)
