### ISSUE TITLE
crash on start on Suse Tmbleweeed 

### ISSUE THREAD

**Issue by AngieSoft** [Helioviewer-Project/JHelioviewer-SWHV#271]
https://swhv.oma.be/datasets/index.php not found ?
----
Uncaught Exception in JHV/SWHV-4.6.4.11044 (amd64 Linux 6.7.7-1-default) JetBrains s.r.o. JRE 21.0.2
Thread: Thread[#71,Thread-8,6,main]
Message: null
Stacktrace:
java.lang.ExceptionInInitializerError
at org.astrogrid.samp.web.WebHubProfile$ServerFactory.createSampXmlRpcServer(WebHubProfile.java:303)
at org.astrogrid.samp.web.WebHubProfile.start(WebHubProfile.java:90)
at org.astrogrid.samp.hub.Hub.startProfile(Hub.java:143)
at org.astrogrid.samp.hub.Hub.runHub(Hub.java:499)
at org.astrogrid.samp.hub.Hub.runHub(Hub.java:543)
at org.helioviewer.jhv.io.SampClient.lambda$init$0(SampClient.java:48)
at java.base/java.lang.Thread.run(Thread.java:1583)

Log:
2024-05-17 15:50:27.396 [main] INFO  org.helioviewer.jhv.JHelioviewer.main - JHelioviewer started with command-line options: 
2024-05-17 15:50:27.409 [main] INFO  org.helioviewer.jhv.JHVGlobals.getVersion - JHV/SWHV-4.6.4.11044 (amd64 Linux 6.7.7-1-default) JetBrains s.r.o. JRE 21.0.2 3.9GB 8CPU
2024-05-17 15:50:29.039 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.JHelioviewer.lambda$main$0 - Start main window
2024-05-17 15:50:29.214 [Location Checker] INFO  org.helioviewer.jhv.io.LocationChecker.lambda$setProximityServer$0 - Location: EU -> default server: IAS
2024-05-17 15:50:30.648 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.JHelioviewer.lambda$main$0 - Load bundled plugins
2024-05-17 15:50:30.841 [AWT-EventQueue-0] SEVERE  org.helioviewer.jhv.plugins.swek.SWEKConfig.parseGroups: Cannot invoke "org.helioviewer.jhv.events.SWEK$Source.name()" because "this.source" is null
2024-05-17 15:50:31.289 [Thread-8] WARNING org.astrogrid.samp.xmlrpc.StandardHubProfile Hub ping method failed: Verbindungsaufbau abgelehnt
2024-05-17 15:50:31.319 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.opengl.GLInfo.get - OpenGL 4.6 (Core Profile) Mesa 23.3.6
2024-05-17 15:50:31.625 [AWT-EventQueue-0] SEVERE  org.helioviewer.jhv.timelines.band.BandDataProvider$BandTypeDownloadCallback.onFailure: Response{protocol=h2, code=404, message=, url=https://swhv.oma.be/datasets/index.php}
2024-05-17 15:50:31.812 [Thread-8] WARNING org.astrogrid.samp.xmlrpc.StandardHubProfile Hub ping method failed: Verbindungsaufbau abgelehnt
2024-05-17 15:50:31.812 [Thread-8] WARNING org.astrogrid.samp.xmlrpc.StandardHubProfile Overwriting /home/uwe/.samp lockfile for apparently dead hub

**Comment by bogdanni** [comment]
The https://swhv.oma.be/datasets/index.php missing is normal, the server was migrated and the timelines will be reinstated in a different form at a later time.

Can you please any stale file /home/uwe/.samp and start it again?

**Comment by AngieSoft** [comment]
here is .samp:


# SAMP Standard Profile lockfile written Fri May 17 18:31:58 UTC 2024
# Note contact URL hostname may be configured using jsamp.localhost property
samp.secret=7af62ac3a3b85fab
samp.hub.xmlrpc.url=http://127.0.0.1:33955/xmlrpc
samp.profile.version=1.3
hub.impl=org.astrogrid.samp.hub.Hub$1
profile.impl=org.astrogrid.samp.xmlrpc.StandardHubProfile
profile.start.date=Fri May 17 18:31:57 UTC 2024

**Comment by AngieSoft** [comment]
remove has no effect, I've already tried it

**Comment by AngieSoft** [comment]
after remove .samp the log:
----
Uncaught Exception in JHV/SWHV-4.6.4.11044 (amd64 Linux 6.7.7-1-default) JetBrains s.r.o. JRE 21.0.2
Thread: Thread[#71,Thread-8,6,main]
Message: null
Stacktrace:
java.lang.ExceptionInInitializerError
at org.astrogrid.samp.web.WebHubProfile$ServerFactory.createSampXmlRpcServer(WebHubProfile.java:303)
at org.astrogrid.samp.web.WebHubProfile.start(WebHubProfile.java:90)
at org.astrogrid.samp.hub.Hub.startProfile(Hub.java:143)
at org.astrogrid.samp.hub.Hub.runHub(Hub.java:499)
at org.astrogrid.samp.hub.Hub.runHub(Hub.java:543)
at org.helioviewer.jhv.io.SampClient.lambda$init$0(SampClient.java:48)
at java.base/java.lang.Thread.run(Thread.java:1583)

Log:
2024-05-17 20:36:24.919 [main] INFO  org.helioviewer.jhv.JHelioviewer.main - JHelioviewer started with command-line options: 
2024-05-17 20:36:24.929 [main] INFO  org.helioviewer.jhv.JHVGlobals.getVersion - JHV/SWHV-4.6.4.11044 (amd64 Linux 6.7.7-1-default) JetBrains s.r.o. JRE 21.0.2 3.9GB 8CPU
2024-05-17 20:36:26.570 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.JHelioviewer.lambda$main$0 - Start main window
2024-05-17 20:36:26.861 [Location Checker] INFO  org.helioviewer.jhv.io.LocationChecker.lambda$setProximityServer$0 - Location: EU -> default server: IAS
2024-05-17 20:36:28.285 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.JHelioviewer.lambda$main$0 - Load bundled plugins
2024-05-17 20:36:28.477 [AWT-EventQueue-0] SEVERE  org.helioviewer.jhv.plugins.swek.SWEKConfig.parseGroups: Cannot invoke "org.helioviewer.jhv.events.SWEK$Source.name()" because "this.source" is null
2024-05-17 20:36:28.976 [AWT-EventQueue-0] INFO  org.helioviewer.jhv.opengl.GLInfo.get - OpenGL 4.6 (Core Profile) Mesa 23.3.6

**Comment by AngieSoft** [comment]
"continue" has no data

![Screenshot_20240517_203745-1](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/25101817/10bc3e95-f154-4e5d-a83f-5e3c438fb9db)

**Comment by bogdanni** [comment]
I installed openSUSE (haven't run that on my computer in more than 20 years!), but I cannot reproduce that in a default configuration.

That crash happens in this [library](https://github.com/mbtaylor/jsamp) which gives access to inter-application communication. That's a pretty robust piece of code.

One supposition is that you run some sort of firewall which blocks local ports from being created (i.e., in your example 33955). Unfortunately this sort of exception (ExceptionInInitializerError) cannot be caught.

If you click Continue at the crash dialog, I think you can avoid this error by going in menu Tools > Settings > disable Load SAMP hub and start JHV again. Hopefully the state of the program allows you that.

**Comment by AngieSoft** [comment]
That's it, no more crash at the start

**Comment by AngieSoft** [comment]
i've no local firewall running on localhost

**Comment by bogdanni** [comment]
Got worried of the message "Verbindungsaufbau abgelehnt". The application sets its locale to English so it should say "Connection refused". I installed a new OS instance localized in another language and, by messing with this .samp file, I can get it to output a localized message. Maybe the message comes from the OS error strings, thus it is localized.

However, I cannot trigger this fatal exception, I'm baffled.
