### ISSUE TITLE
 The BROWSE action failed on Ubuntu 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer-SWHV#63]
Hello, 

When I launch JHelioviewer I have a message saying that a new version is available .
The "Download" button leads to a failure  : " The BROWSE action is not supported on the current platform!"

command 
<pre>
root@sol-palinger:/usr/local/jhv-2.12.0.8493# java -jar JHelioviewer.jar
</pre>

system:
<pre>
root@sol-palinger:/usr/local/jhv-2.12.0.8493# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
</pre>

<pre>
root@sol-palinger:/usr/local/jhv-2.12.0.8493# java -jar JHelioviewer.jar
2018-03-27 12:05:04,534 [main] INFO  root - JHelioviewer started with command-line options:
2018-03-27 12:05:04,596 [main] INFO  root - Running JHV/SWHV-2.12.0.8493 (amd64 Linux 4.4.0-83-generic) Oracle Corporation JRE 1.8.0_151
2018-03-27 12:05:05,213 [AWT-EventQueue-0] INFO  root - Start main window
2018-03-27 12:05:06,024 [JHVWorker-MAIN--PositionLoad] ERROR root - Error reading JSON: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2018-03-27 12:05:06,024 [JHVWorker-MAIN--PositionLoad] ERROR root - Error reading JSON: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
libEGL warning: DRI2: failed to authenticate
2018-03-27 12:05:06,713 [AWT-EventQueue-0] INFO  root - Load bundled plugins
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.xmlrpc.XmlRpcKit createDefaultInstance
INFO: Creating default XmlRpcInstance: jsamp.xmlrpc.impl=null
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.xmlrpc.XmlRpcKit getInstance
INFO: Default XmlRpcInstance is internal
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.hub.Hub runExternalHub
INFO: Starting external hub
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.hub.Hub runExternalHub
INFO: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -classpath JHelioviewer.jar org.astrogrid.samp.hub.Hub -mode client-gui
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.xmlrpc.StandardClientProfile getLockUrl
INFO: Using default Standard Profile lockfile: /root/.samp
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.httpd.HttpServer start
INFO: Server http://127.0.0.1:38975 starting
Mar 27, 2018 10:05:07 AM org.astrogrid.samp.client.HubConnector$6 run
INFO: SAMP autoconnection attempt succeeded
2018-03-27 12:05:07,450 [AWT-EventQueue-0-Display-.x11_:0-1-EDT-1] INFO  root - GLInfo > Version string: 3.3.0 NVIDIA 304.135
2018-03-27 12:05:08,022 [AWT-EventQueue-0] INFO  root - Found newer version 2.12.1.8546
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.browse(Desktop.java:381)
	at org.helioviewer.jhv.JHVGlobals.openURL(JHVGlobals.java:152)
	at org.helioviewer.jhv.gui.dialogs.NewVersionDialog$2.actionPerformed(NewVersionDialog.java:42)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.jidesoft.dialog.StandardDialog.show(Unknown Source)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.helioviewer.jhv.gui.dialogs.TextDialog.showDialog(TextDialog.java:53)
	at org.helioviewer.jhv.JHVUpdate.lambda$run$0(JHVUpdate.java:68)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

</pre>

**Comment by bogdanni** [comment]
This is not an error, it merely states that Java is not able to invoke your desktop environment on that particular URI. This will not be attempted anymore in the next version.

Please just download it from http://swhv.oma.be/download/ or, in your case, http://swhv.oma.be/download_test/test_ias/.

**Comment by bogdanni** [comment]
I suggest to not run this program as root. Since version 2.12 it is able to accept incoming network connections for the SAMP protocol.

There is also an 161/162 update for Java 8.
