### ISSUE TITLE
Bad parameter or other API misuse

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer-SWHV#70]
Hello, 

I launch JHelioviewer from command line I have got an error 

<pre>
root@sol-palinger:/usr/local/jhv-2.13.1.8623# java -jar JHelioviewer.jar -request ./request.json  
2018-05-18 15:47:51,863 [main] INFO  root - JHelioviewer started with command-line options: -request ./request.json
2018-05-18 15:47:51,888 [main] INFO  root - Running JHV/SWHV-2.13.1.8623 (amd64 Linux 4.4.0-83-generic) Oracle Corporation JRE 1.8.0_171
2018-05-18 15:47:52,527 [AWT-EventQueue-0] INFO  root - Start main window
libEGL warning: DRI2: failed to authenticate
2018-05-18 15:47:54,015 [AWT-EventQueue-0] INFO  root - Load bundled plugins
May 18, 2018 1:47:54 PM org.astrogrid.samp.xmlrpc.XmlRpcKit createDefaultInstance
INFO: Creating default XmlRpcInstance: jsamp.xmlrpc.impl=null
May 18, 2018 1:47:54 PM org.astrogrid.samp.xmlrpc.XmlRpcKit getInstance
INFO: Default XmlRpcInstance is internal
May 18, 2018 1:47:54 PM org.astrogrid.samp.hub.Hub runExternalHub
INFO: Starting external hub
May 18, 2018 1:47:54 PM org.astrogrid.samp.hub.Hub runExternalHub
INFO: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -classpath JHelioviewer.jar org.astrogrid.samp.hub.Hub -mode client-gui
May 18, 2018 1:47:54 PM org.astrogrid.samp.xmlrpc.StandardClientProfile getLockUrl
INFO: Using default Standard Profile lockfile: /root/.samp
May 18, 2018 1:47:54 PM org.astrogrid.samp.httpd.HttpServer start
INFO: Server http://127.0.0.1:35860 starting
May 18, 2018 1:47:54 PM org.astrogrid.samp.client.HubConnector$6 run
INFO: SAMP autoconnection attempt succeeded
2018-05-18 15:47:54,782 [AWT-EventQueue-0-Display-.x11_:0-1-EDT-1] INFO  root - GLInfo > Version string: 3.3.0 NVIDIA 304.135
2018-05-18 15:47:57,382 [JHVWorker-MAIN--LoadRequest] ERROR root - Failed to select
org.sqlite.SQLiteException: [SQLITE_MISUSE]  Library used incorrectly (bad parameter or other API misuse)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.DB.execute(DB.java:806)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
	at org.helioviewer.jhv.database.DataSourcesDB.doSelect(DataSourcesDB.java:72)
	at org.helioviewer.jhv.io.APIRequest.fromRequestJson(APIRequest.java:94)
	at org.helioviewer.jhv.io.LoadRequestTask.backgroundWork(LoadRequestTask.java:23)
	at org.helioviewer.jhv.io.LoadRequestTask.backgroundWork(LoadRequestTask.java:12)
	at org.helioviewer.jhv.threads.JHVWorker.doInBackground(JHVWorker.java:23)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-18 15:47:57,383 [JHVWorker-MAIN--LoadRequest] ERROR root - An error occured while opening the remote file: 
java.io.IOException: Invalid response for nullsourceId=0&startTime=2012-03-06T12:00:00Z&endTime=2012-03-06T20:00:00Z&cadence=3600&jpip=true&verbose=true&linked=true
	at org.helioviewer.jhv.io.APIRequestManager.requestRemoteFile(APIRequestManager.java:51)
	at org.helioviewer.jhv.io.LoadViewTask.requestAndOpenRemoteFile(LoadViewTask.java:83)
	at org.helioviewer.jhv.io.LoadRequestTask.backgroundWork(LoadRequestTask.java:24)
	at org.helioviewer.jhv.io.LoadRequestTask.backgroundWork(LoadRequestTask.java:12)
	at org.helioviewer.jhv.threads.JHVWorker.doInBackground(JHVWorker.java:23)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.URISyntaxException: Illegal character in scheme name at index 12: nullsourceId=0&startTime=2012-03-06T12:00:00Z&endTime=2012-03-06T20:00:00Z&cadence=3600&jpip=true&verbose=true&linked=true
	at org.helioviewer.jhv.io.NetClient.of(NetClient.java:29)
	at org.helioviewer.jhv.io.JSONUtils.get(JSONUtils.java:39)
	at org.helioviewer.jhv.io.APIRequestManager.requestRemoteFile(APIRequestManager.java:18)
	... 10 more
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 12: nullsourceId=0&startTime=2012-03-06T12:00:00Z&endTime=2012-03-06T20:00:00Z&cadence=3600&jpip=true&verbose=true&linked=true
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3048)
	at java.net.URI.<init>(URI.java:588)
	at org.helioviewer.jhv.io.NetClient.of(NetClient.java:27)
	... 12 more
</pre>

Restarting several times (4 times in my case ) => no more problems .
Do you have a recommendation to avoid that ?
P. 
IAS

**Comment by Katarni** [comment]
@PabloA-dev-coder, can u explain please. u just repeat this 4 times?

**Comment by PabloA-dev-coder** [comment]
Hello, 
This means that this error was not reproducible and that it disappeared after 4 tries.
It seems to have been corrected as mentioned by @bogdanni 
Best regards, 
Pablo

**Comment by Katarni** [comment]
okey, thanks
